export const HOME_ROUTES = {
  HOME: "/",
  RESTAURANTS: "/restaurants",
  PRICING: "/pricing",
  FAQ: "/faq",
  CONTACT_EMAIL: "mailto:help@ulodine.com",
  CONTACT_PHONE: "tel:+2349063213825",
};

export const PAGE_ROUTES = {
  ABOUT: "/about-us",
};

export const AUTH_ROUTES = {
  RES_LOGIN: "http://localhost:5000/auth/login",
  RES_SIGNUP: "http://localhost:5000/auth/signup",
  RES_LOGOUT: "http://localhost:5000/logout",
  RES_RECOVER_PASSWORD: "http://localhost:5000/auth/forgot-password",
  RES_VERIFY_EMAIL: "http://localhost:5000/auth/verify-email",
  RES_NEW_PASSWORD: "http://localhost:5000/auth/new-password",
  RES_DELETE_ACCOUNT: "http://localhost:5000/auth/delete-account",
  CUS_LOGIN: "http://localhost:3000/login",
  CUS_SIGNUP: "http://localhost:3000/signup",
  CUS_LOGOUT: "http://localhost:3000/logout",
  CUS_VERIFY_EMAIL: "http://localhost:3000/verify-email",
  CUS_RECOVER_PASSWORD: "http://localhost:3000/recover-password",
  CUS_NEW_PASSWORD: "http://localhost:3000/new-password",
};

export const RESTAURANT_MANAGEMENT_ROUTES = {
  OVERVIEW: "http://localhost:5000/management/overview",
  ORDERS: "http://localhost:5000/management/orders",
  MENU_MANAGEMENT: "http://localhost:5000/management/menu-management",
  BILLING: "http://localhost:5000/management/billing",
  REPORTS: "http://localhost:5000/management/reports-and-analytics",
  QR_CODE: "http://localhost:5000/management/qr-code",
  SETTINGS: "http://localhost:5000/management/settings",
  LOGOUT: "http://localhost:5000/management/logout",
  KDS: "http://localhost:5000/management/kds",
  TABLES: "http://localhost:5000/management/tables",
};

export const RESTAURANT_API_ROUTES = {
  LOGIN: "/api/auth/login",
  SIGNUP: "/api/auth/register",
  GET_RESTAURANT_DETAILS: "/restaurant/details",
  GET_RESTAURANT_ORDERS: "/restaurant/orders",
  GET_MENU_ITEMS: "/restaurant/menu-items",
  ADD_MENU_ITEM: "/restaurant/menu-items/add",
  UPDATE_MENU_ITEM: "/api/restaurant/menu/update",
  DELETE_MENU_ITEM: "/api/restaurant/menu/delete",
  GET_REPORTS: "/restaurant/reports",
  GET_QR_CODE: "/restaurant/qr-code",
  UPDATE_SETTINGS: "/restaurant/settings/update",
  LOGOUT: "/restaurant/logout",
  GET_RESTAURANT_BY_ID: "/api/restaurants/:id",
  UPDATE_BUSINESS_BANNER: "/api/restaurants/:id/banner",
  UPDATE_BUSINESS_DESCRIPTION: "/api/restaurants/:id/description",
  UPDATE_BUSINESS_EMAIL: "/api/restaurants/:id/email",
  UPDATE_BUSINESS_PHONE: "/api/restaurants/:id/phone",
  UPDATE_BUSINESS_ADDRESS: "/api/restaurants/:id/address",
  UPDATE_BUSINESS_PASSWORD: "/api/restaurants/:id/password",
  UPDATE_BUSINESS_NAME: "/api/restaurants/:id/name",
  UPDATE_BUSINESS_CUISINE: "/api/restaurants/:id/cuisine",
  BLOCK_BUSINESS: "/api/restaurants/:id/block",
  UNBLOCK_BUSINESS: "/api/restaurants/:id/unblock",
  DELETE_BUSINESS: "/api/restaurants/:id",
  CREATE_ORDER: "/api/orders",
  GET_ORDER_BY_ID: "/api/orders/:id/:restaurantId",
  GET_ORDERS_BY_RESTAURANT_ID: "/api/orders/restaurant/:restaurantId",
  GET_ORDERS_BY_CUSTOMER_ID: "/api/orders/customer/:customerId",
  GET_ALL_ORDERS: "/api/orders",
  CANCEL_ORDER: "/api/cancel/:id/:customerId",
  GET_ORDER_BY_REFERENCE: "/api/reference/:reference/:restaurantId",
  GET_ORDERS_BY_STATUS: "/api/filter/status/:businessId/:status",
  FILTER_ORDERS_BY_DATE: "/api/filter/date/:businessId/:startDate/:endDate",
  UPDATE_ORDER_STATUS: "/api/update/:businessId/:orderId",
  CREATE_MENU: "/api/menu",
  GET_MENU_BY_ID: "/api/menu/:id",
  GET_MENUS_BY_RESTAURANT_ID: "/api/restaurant/menu/all",
  GET_ALL_MENUS: "/api/menu",
  GET_MENU_BY_NAME: "/api/menu/name/:name",
  GET_MENU_BY_CATEGORY: "/api/menu/category/:category",
  GET_MENU_BY_PRICE: "/api/menu/price/:price",
  GET_MENU_BY_RATING: "/api/menu/rating/:rating",
  FILTER_MENU_BY_STOCK_STATUS: "/api/menu/filter/stock/:businessId/:status",
  FILTER_MENU_BY_STATUS: "/api/menu/filter/status/:businessId/:status",
  FILTER_MENU_BY_CATEGORY: "/api/menu/filter/category/:businessId/:category",
  UPDATE_MENU_STATUS: "/api/restaurant/menu/status",
  UPDATE_MENU_STOCK_STATUS: "/api/restaurant/menu/stock",
  DELETE_MENU: "/api/restaurant/menu/delete",
};

export const CUSTOMER_ROUTES = {
  HOME: "http://localhost:3000/home",
  ORDERS: "http://localhost:3000/orders",
  BROWSE: "http://localhost:3000/restaurants",
  PROFILE: "http://localhost:3000/profile",
  CART: "http://localhost:3000/cart",
  NOTIFICATIONS: "http://localhost:3000/notifications",
  CHECKOUT: "http://localhost:3000/cart/checkout",
  PAYMENT_SUCCESS: "http://localhost:3000/payment/success",
  PAYMENT_FAILED: "http://localhost:3000/payment/failed",
  SETTINGS: "http://localhost:3000/settings",
  LOGOUT: "http://localhost:3000/logout",
  SCAN: "http://localhost:3000/scan",
} as const;

export const RESTAURANT_ROUTES = {
  DETAILS: (id: string | number) => `http://localhost:3000/restaurants/${id}`,
  REVIEWS: (id: string | number) => `http://localhost:3000/restaurants/reviews/${id}`,
} as const;
