export const HOME_ROUTES = {
  HOME: "/",
  RESTAURANTS: "/restaurants",
  PRICING: "/pricing",
};

export const PAGE_ROUTES = {
  ABOUT: "/about-us",
};

export const AUTH_ROUTES = {
  RES_LOGIN: "/restaurant/login",
  RES_SIGNUP: "/restaurant/signup",
  RES_LOGOUT: "/logout",
};

export const RESTAURANT_MANAGEMENT_ROUTES = {
  OVERVIEW: "/restaurant/management/overview",
  ORDERS: "/restaurant/management/orders",
  MENU_MANAGEMENT: "/restaurant/management/menu-management",
  REPORTS: "/restaurant/management/reports-and-analytics",
  QR_CODE: "/restaurant/management/qr-code",
  SETTINGS: "/restaurant/management/settings",
  LOGOUT: "/restaurant/management/logout",
};

export const RESTAURANT_API_ROUTES = {
  LOGIN: "/api/auth/login",
  SIGNUP: "/api/auth/register",
  GET_RESTAURANT_DETAILS: "/restaurant/details",
  GET_RESTAURANT_ORDERS: "/restaurant/orders",
  GET_MENU_ITEMS: "/restaurant/menu-items",
  ADD_MENU_ITEM: "/restaurant/menu-items/add",
  UPDATE_MENU_ITEM: "/restaurant/menu-items/update",
  DELETE_MENU_ITEM: "/restaurant/menu-items/delete",
  GET_REPORTS: "/restaurant/reports",
  GET_QR_CODE: "/restaurant/qr-code",
  UPDATE_SETTINGS: "/restaurant/settings/update",
  LOGOUT: "/restaurant/logout",
  GET_RESTAURANT_BY_ID: "/api/restaurants/:id",
  UPDATE_BUSINESS_BANNER: "/api/restaurants/:id/banner",
  UPDATE_BUSINESS_DESCRIPTION: "/api/restaurants/:id/description",
  UPDATE_BUSINESS_EMAIL: "/api/restaurants/:id/email",
  UPDATE_BUSINESS_PHONE: "/api/restaurants/:id/phone",
  UPDATE_BUSINESS_ADDRESS: "/api/restaurants/:id/address",
  UPDATE_BUSINESS_PASSWORD: "/api/restaurants/:id/password",
  UPDATE_BUSINESS_NAME: "/api/restaurants/:id/name",
  UPDATE_BUSINESS_CUISINE: "/api/restaurants/:id/cuisine",
  BLOCK_BUSINESS: "/api/restaurants/:id/block",
  UNBLOCK_BUSINESS: "/api/restaurants/:id/unblock",
  DELETE_BUSINESS: "/api/restaurants/:id",
  CREATE_ORDER: "/api/orders",
  GET_ORDER_BY_ID: "/api/orders/:id/:restaurantId",
  GET_ORDERS_BY_RESTAURANT_ID: "/api/orders/restaurant/:restaurantId",
  GET_ORDERS_BY_CUSTOMER_ID: "/api/orders/customer/:customerId",
  GET_ALL_ORDERS: "/api/orders",
  CANCEL_ORDER: "/api/cancel/:id/:customerId",
  GET_ORDER_BY_REFERENCE: "/api/reference/:reference/:restaurantId",
  GET_ORDERS_BY_STATUS: "/api/filter/status/:businessId/:status",
  FILTER_ORDERS_BY_DATE: "/api/filter/date/:businessId/:startDate/:endDate",
  UPDATE_ORDER_STATUS: "/api/update/:businessId/:orderId",
  CREATE_MENU: "/api/menu",
  GET_MENU_BY_ID: "/api/menu/:id",
  GET_MENUS_BY_RESTAURANT_ID: "/api/menu/restaurant/:restaurantId",
  GET_ALL_MENUS: "/api/menu",
  GET_MENU_BY_NAME: "/api/menu/name/:name",
  GET_MENU_BY_CATEGORY: "/api/menu/category/:category",
  GET_MENU_BY_PRICE: "/api/menu/price/:price",
  GET_MENU_BY_RATING: "/api/menu/rating/:rating",
  FILTER_MENU_BY_STOCK_STATUS: "/api/menu/filter/stock/:businessId/:status",
  FILTER_MENU_BY_STATUS: "/api/menu/filter/status/:businessId/:status",
  FILTER_MENU_BY_CATEGORY: "/api/menu/filter/category/:businessId/:category",
  UPDATE_MENU_STATUS: "/api/menu/status/:businessId/:menuId/:status",
  UPDATE_MENU_STOCK_STATUS: "/api/menu/stock/:businessId/:id/:status",
  DELETE_MENU: "/api/menu/:businessId/:menuId",
};
